### ISSUE TITLE
Re-upload u'r mod, please : death link

### ISSUE THREAD

**Issue by bmateu** [TomyLobo/ccredbus#1]
Can you re-upload your mod / give me a version? I've lost the zip mod file... 
        u'r moi is fabulous, i try it and it's very very nice use redbus peripheral with computercraft. 
Britaliope

**Comment by TomyLobo** [comment]
It should work again now. I also fixed the link for http://computercraft.info/forums2/index.php?/topic/12493-147-cc-1481-ccnoise-generate-custom-sounds/ and I put both jars on github as well. they shouldn't disappear again :)
